Feature poi tests
TomStrong/DevOpsAssessment pull request #61
Opened 2023-11-01 14:35 UTC by ali1373107

adding poi route has been tested and test passed. 
sum.js file deleted. its not necessarily to have it.

2023-11-01 17:04 UTC, TomStrong requested changes
Please address the comments I have made:

- Remove sum.js
- Explain why we need test-esm.js

2023-11-01 17:04 UTC, TomStrong commented on sum.js
sum.js file appears to still be present

2023-11-01 17:04 UTC, TomStrong commented on test-esm.js
Is this file necessary? What does it do?

2023-11-01 17:06 UTC, TomStrong requested changes
Change file name as shown in comments

2023-11-01 17:06 UTC, TomStrong commented on tests/routs.test.js
This file is incorrectly named

2023-11-02 13:43 UTC, ali1373107 commented on test-esm.js
the reason i added this code to your test file is to enable the use of ES6 module syntax in your tests. but i deleted unnecessarily files. check it and let me know if any other changes required

2023-11-02 14:53 UTC, 5thaks07 approved these changes
Very nice mate

2023-11-02 17:34 UTC, TomStrong approved these changes

2023-11-02 17:51 UTC, merged